spring:
  application:
    name: springbatchdemo
  main:
    web-application-type: none #spring boot web flux starter automatically starts up a server, this is needed to override that.
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./target/db/test1
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  liquibase:
    enabled: true
  batch:
    job:
      enabled: false

logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
# server:
#   port: 8090
